site: michaeldaryl
url: https://michaeldaryl.live
title: michaeldaryl
description: write-ups and stories
twitter:
  username: michaeldaryl_
  card: summary
  creator: Michael Daryl Mayo
author:
  twitter: michaeldaryl_
  name: Michael Daryl Mayo
  avatar:
  email: michaeldaryl.code@gmail.com
  url: michaeldaryl.live
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

domain: michaeldaryl.live      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
